version: '3.8'
# name: transcendence

services:
  db:
    image: postgres:latest
    container_name: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      DATABASE_URL: $DATABASE_URL
      JWT_SECRET: $JWT_SECRET
      OTP_SECRET: $OTP_SECRET
      COMMON_BASE_URL: $COMMON_BASE_URL
    depends_on:
      - "db"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app

volumes:
  db_data:

networks:
  default:
    name: kent
